openapi: 3.0.3
info:
  title: Mijn Amsterdam koppel api met Mijn Belastingen
  description: Dit is het koppelstuk tussen Mijn Amsterdam en Mijn Belastingen
  version: 1.0.0
  contact:
    email: datapunt@amsterdam.nl
    name: Datapunt Support
    url: https://data.amsterdam.nl/
paths:
  /belastingen/get:
    parameters:
      - name: Authorization
        in: header
        description: Bearer token
        required: true
        schema:
          type: string
    get:
      summary: Informatie m.b.t. belasting tips en/of meldingen op basis van BSN
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    nullable: true
                    $ref: "#/components/schemas/UserInfo"
                  status:
                    type: string
                    enum:
                      - "OK"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /status/health:
    get:
      summary: returns "OK"
      responses:
        "200":
          description: Returns "OK"
          content:
            application/json:
              schema:
                type: string
                enum:
                  - "OK"

components:
  schemas:
    UserInfo:
      type: object
      properties:
        isKnown:
          type: boolean
        notifications:
          type: array
          items:
            $ref: "#/components/schemas/MyNotification"
        tips:
          type: array
          items:
            $ref: "#/components/schemas/Tip"
    ErrorResponse:
      type: object
      properties:
        status:
          type: string
          enum:
            - "ERROR"
        message:
          type: string
    Tip:
      type: object
      properties:
        datePublished:
          type: string
          format: date-time
          example: '2020-01-28T13:11:51Z'
        description:
          type: string
          example: 'Er staat nog een aanslag open van u. Zorg voor tijdige betaling.'
        id:
          type: string
          example: 'belasting-4'
        priority:
          type: number
          example: 1
        title:
          type: string
          example: 'Betaal uw aanslagen'
        link:
          type: object
          properties:
            title:
              type: string
              example: 'Betaal direct'
            to:
              type: string
              example: 'https://localhost/aanslagen.php'
        reason:
          type: string
          example: 'U krijgt deze tip omdat u nog niet via automatische incasso betaalt'
    MyNotification:
      type: object
      properties:
        datePublished:
          type: string
          format: 'date-time'
          example: '2020-01-28T13:11:51Z'
        description:
          type: string
          example: 'Er staat nog een aanslag open van u. Zorg voor tijdige betaling.'
        id:
          type: string
          example: 'belasting-4'
        priority:
          type: number
          example: 1
        title:
          type: string
          example: 'Betaal uw aanslagen'
        link:
          type: object
          properties:
            title:
              type: string
              example: 'Betaal direct'
            to:
              type: string
              example: 'https://localhost/aanslagen.php'
